### ISSUE TITLE
Saving to database takes a long time on linux

### ISSUE THREAD

**Issue by ryanzj725** [Castronova/EMIT#355]
After running an simulation saving takes a long time.

**Comment by ryanzj725** [comment]
here it the error I got when testing: 

Exception in thread Engine_RunFeedForward:
Traceback (most recent call last):
  File "/home/ryan/miniconda2/envs/emit/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/ryan/miniconda2/envs/emit/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/ryan/emit/EMIT/coordinator/run.py", line 161, in run_feed_forward
    update.update_links_feed_forward(obj, links[modelid], oei, spatial_maps)
  File "/home/ryan/emit/EMIT/coordinator/update.py", line 131, in update_links_feed_forward
    mvals = transform(tmap, svals)
  File "/home/ryan/emit/EMIT/transform/time.py", line 22, in transform
    return source_values[temporal_map]
IndexError: index 1466 is out of bounds for axis 1 with size 1466

**Comment by Castronova** [comment]
@ryanzj725 How did you execute the simulation?  Did you run the unittest or build a configuration?

**Comment by Castronova** [comment]
@ryanzj725 Can you try this again by running `tests.db.test_sqlite_db.py`?
